# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'MarketPlace' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'AlamofireObjectMapper', '~> 3.0'
 pod 'Kingfisher', '~> 2.4'
 pod 'AlamofireImage', '~> 2.0'
 pod 'Alamofire', '~> 3.4'
 pod 'ReachabilitySwift', '~> 2.0-beta1'
 pod 'Fabric'
 pod 'Crashlytics'
  # Pods for MarketPlace

  target 'MarketPlaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarketPlaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
